export const images = {
  bg_wallpaper: require('./source/bg.png'),
  default: require('./source/default.png'),
  userDefault: require('./source/user_default.png'),
  userCoverDefault: require('./source/user_cover_default.png'),
  welcome_1: require('./source/welcome_1.png'),
  welcome_2: require('./source/welcome_2.png'),
  welcome_3: require('./source/welcome_3.png'),
  tool_bar_soscious: require('./drawable/tool_bar_soscious.png'),
  img404: require('./source/img_404.png'),
  register_success: require('./drawable/register_success.png'),
  errorBase: require('./source/error_base.png'),
  successBase: require('./source/success_base.png'),
  registerSuccess: require('./source/register_success.png'),
  noFollower: require('./source/noFollowers.png'),
  noFollowing: require('./source/NoFollowing.png'),
  noSearch: require('./source/noSearch.png'),
  discard: require('./source/discard.png'),
  notificationEmpty: require('./source/notification_empty.png'),
  chatsEmpty: require('./source/chat_empty.png'),
  emptyChatFriend: require('./source/empty_chat_friend.png'),
  discardPost: require('./source/discard-post.png'),
  createOrgInfo: require('./source/create_org.png'),
  createOrgSuccess: require('./source/success_created.png'),
  projectHeader: require('./source/projects-header.png'),
  feedBanner: require('./source/feed-banner.png'),
  fileAttachmentDefault: require('./source/attach-file.png'),
  pageDefault: require('./source/page-default.png'),
};

export type ImageTypes = keyof typeof images;
